function DOF=DOF_from_all_angs_Body(all_angs1)
psi_abd=all_angs1(3,1);
theta_abd=all_angs1(2,1);
phi_abd=all_angs1(1,1);
psi_thorax=all_angs1(3,2);
theta_thorax=all_angs1(2,2);
phi_thorax=all_angs1(1,2);
psi_hipR=all_angs1(3,10);
theta_hipR=all_angs1(2,10);
phi_hipR=all_angs1(1,10);
psi_hipL=all_angs1(3,13);
theta_hipL=all_angs1(2,13);
phi_hipL=all_angs1(1,13);
phi_kneeR=all_angs1(1,11);
psi_kneeR=all_angs1(3,11);
theta_kneeR=all_angs1(2,11);
phi_kneeL=all_angs1(1,14);
psi_kneeL=all_angs1(3,14);
theta_kneeL=all_angs1(2,14);
phi_ankleR=all_angs1(1,12);
psi_ankleR=all_angs1(3,12);
theta_ankleR=all_angs1(2,12);
phi_ankleL=all_angs1(1,15);
psi_ankleL=all_angs1(3,15);
theta_ankleL=all_angs1(2,15);
psi_head=all_angs1(3,3);
theta_head=all_angs1(2,3);
phi_head=all_angs1(1,3);
psi_shR=all_angs1(3,4);
theta_shR=all_angs1(2,4);
phi_shR=all_angs1(1,4);
psi_shL=all_angs1(3,7);
theta_shL=all_angs1(2,7);
phi_shL=all_angs1(1,7);
phi_wrR=all_angs1(1,6);
phi_wrL=all_angs1(1,9);
psi_wrR=all_angs1(3,6);
psi_wrL=all_angs1(3,9);
theta_wrR=all_angs1(2,6);
theta_wrL=all_angs1(2,9);

phi_elR=all_angs1(1,5);
psi_elR=all_angs1(3,5);
theta_elR=all_angs1(2,5);

theta_elL=all_angs1(2,8);
phi_elL=all_angs1(1,8);
psi_elL=all_angs1(3,8);

DOF=[0 0 0;
    psi_abd theta_abd phi_abd;
    psi_thorax theta_thorax phi_thorax;
    psi_head theta_head phi_head;
    psi_shR theta_shR phi_shR;
    psi_shL theta_shL phi_shL;
    psi_elR theta_elR phi_elR;
    psi_elL theta_elL phi_elL;
    psi_wrR theta_wrR phi_wrR;
    psi_wrL theta_wrL phi_wrL;
    psi_hipR theta_hipR phi_hipR;
    psi_hipL theta_hipL phi_hipL;
    psi_kneeR theta_kneeR phi_kneeR;
    psi_kneeL theta_kneeL phi_kneeL;
    psi_ankleR theta_ankleR phi_ankleR;
    psi_ankleL theta_ankleL phi_ankleL];
